# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "foursquare-api"
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["nroberts269"]
  s.date = "2013-01-16"
  s.description = "foursquare-api is a Ruby wrapper for the new Foursqauare V2 API"
  s.email = "nroberts269@live.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "foursquare-api.gemspec",
    "lib/foursquare.rb",
    "lib/foursquare_checkins.rb",
    "lib/foursquare_node.rb",
    "lib/foursquare_photo.rb",
    "lib/foursquare_settings.rb",
    "lib/foursquare_tips.rb",
    "lib/foursquare_user.rb",
    "lib/foursquare_venue.rb",
    "test/helper.rb",
    "test/test_foursquare-api.rb"
  ]
  s.homepage = "http://github.com/nroberts269/foursquare-api"
  s.licenses = ["GPL"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "%Q{foursquare-api is a Ruby wrapper for the new Foursqauare V2 API}"
  s.test_files = [
    "test/helper.rb",
    "test/test_foursquare-api.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

